apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-elasticsearch-pv-claim
  labels:
    app: elastic
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
