apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elastic-kibana
  namespace: utilities
  labels:
    app: elastic
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elastic
        tier: kibana
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:6.3.2
        name: kibana
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch.db.svc.cluster.stouffcapital.tech:9200
        ports:
        - containerPort: 5601
          name: kibana
      - image: machinedata/oauth2_proxy:2.2
        name: kibana-proxy
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: kibana
                key: oauth2-clientId
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: kibana
                key: oauth2-clientSecret
          - name: OAUTH2_PROXY_UPSTREAM
            value: http://localhost:5601/
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: kibana
                key: oauth2-cookieSecret
          - name: OAUTH2_PROXY_HTTP_ADDRESS
            value: 0.0.0.0:4180
          - name: OAUTH2_PROXY_EMAIL_DOMAIN
            value: stouffcapital.com
          - name: OAUTH2_PROXY_REDIRECT_URL
            value: https://kibana.stouffcapital.tech/oauth2/callback
        ports:
        - containerPort: 4180
          name: proxy
